services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: metar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-stack-server
      --requirepass metar_password
      --save 60 1
      --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "metar_password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    container_name: metar_postgres
    environment:
      POSTGRES_DB: vatsim_metar
      POSTGRES_USER: metar_user
      POSTGRES_PASSWORD: metar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metar_user -d vatsim_metar"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    name: metar_redis_data
  postgres_data:
    name: metar_postgres_data
